aishop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
    path('products/',include('products.urls'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index')

]

member/urls.py
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('forget/',views.forget,name='forget'),
    path('create',views.create,name='create')
]

products/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter
from django.conf.urls import url, include
from django.contrib import admin

app_name='products'
urlpatterns = [
    path('', views.index,name='index'),
    path('products', views.products,name='list')
]

home/models.py
from django.db import models

# Create your models here.

member/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    username = models.TextField()
    password = models.TextField()
    useremail= models.TextField()
    name= models.TextField()
    userbirth = models.TextField()
    
    class Meta:
        db_table = "members"

products/models.py
from django.db import models

# Create your models here.
class Drinks(models.Model):
    name = models.CharField(max_length=50,null=False)
    price = models.IntegerField(null=False)
    qt = models.IntegerField(null=False)
    image = models.CharField(max_length=200,null=False)

    class Meta:
        db_table = "Drinks"

class Foods(models.Model):
    name = models.CharField(max_length=50,null=False)
    price = models.IntegerField(null=False)
    qt = models.IntegerField(null=False)
    image = models.CharField(max_length=200,null=False)

    class Meta:
        db_table = "Foods"

class Orders(models.Model):
    order_number = models.IntegerField(null=False)
    user_name = models.CharField(max_length=50,null=False)
    product_name = models.CharField(max_length=50,null=False)
    price = models.IntegerField(null=False)
    qt = models.IntegerField(null=False)
    image = models.CharField(max_length=200,null=False)
    datetime = models.TextField(max_length=200,null=False)

    class Meta:
        db_table = "Orders"
        
class Member(models.Model):
    username = models.CharField(max_length=20,null=False)
    password = models.CharField(max_length=10,null=False)
    useremail = models.EmailField(max_length=100,blank=True)
    userbirth = models.DateField(null=False)
    
    class Meta:
        db_table = "members"

home/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request,'home/index.html',locals())

member/views.py
from django.shortcuts import render,redirect
from .models import Member
from django.http import HttpResponse

# Create your views here.
def index(request):
    if 'name' in request.COOKIES:
        return render(request,'member/memberarea.html',locals())
    else:
        response = HttpResponse("<script>alert('請先登入喔!');location.href='/member/login'</script>")
        return response


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        pwd = request.POST['userpassword']
        member = Member.objects.filter(username=username,password=pwd).values('username')
        if member:
            response = HttpResponse("<script>alert('登入成功');location.href='/'</script>")
            if 'rememberme' in request.POST:
                expiresdate = datetime.datetime.now() + datetime.timedelta(days=7)
                response.set_cookie("name",member[0]['username'],expires=expiresdate)
            else:
                response.set_cookie("name",member[0]['username'])
        else:
            response = HttpResponse("<script>alert('密碼錯誤');location.href='/member/login'</script>")
        return response
    title = "會員登入"
    return render(request,'member/login.html',locals())

def logout(request):
   response = HttpResponse("<script>alert('登出成功');location.href='/member/login'</script>")
   response.delete_cookie('name')
   return response

def create(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        useremail = request.POST["useremail"]
        userbirth = request.POST["userbirth"]

        # EMAIL_USE_TLS = True 
        # EMAIL_HOST = "smtp.gmail.com"
        # EMAIL_PORT = 587
        # EMAIL_HOST_USER = "a11118825@gmail.com"
        # EMAIL_HOST_PASSWORD = "a63475566"
        # from_email = EMAIL_HOST_USER
        # to_list = useremail

        # # email_conn即為SMTP物件，建立SMTP連線
        # email_conn=smtplib.SMTP(EMAIL_HOST,EMAIL_PORT)
        # email_conn.ehlo()
        # #TTLS安全認證機制，必須使用TTLS protocol來進行連結傳輸,故叫喚starttls這個函式
        # email_conn.starttls()
        # email_conn.login(EMAIL_HOST_USER, EMAIL_HOST_PASSWORD)
        # email_conn.sendmail(from_email, to_list, "Hi Welcome, now you are one of us!")
        # email_conn.quit()

        #todo 接收到的會員資料寫進資料庫
        Member.objects.create(username=username,password=password,useremail=useremail,userbirth=userbirth)
        
        #todo 新增完成後轉到http://localhost:8000/member
        return redirect("/member")
       
    title = "會員新增" 
    return render(request,'member/create.html',locals())

def forget(request):
    if request.method == 'POST':      
        useremail=request.POST['useremail']
        response = HttpResponse("<script>alert('修改密碼信件已寄出');location.href='/member/index'</script>")
        return response
    
    else:
        return render(request,'member/forget.html',locals())

products/views.py
from django.shortcuts import render

# Create your views here.
from .models import Drinks
from .models import Foods
from .models import Orders
from .models import Member
from .serializers import DrinksSerializer
from .serializers import FoodsSerializer
from .serializers import OrdersSerializer
from .serializers import MemberSerializer

from rest_framework import viewsets


# Create your views here.
class DrinksViewSet(viewsets.ModelViewSet):
    queryset = Drinks.objects.all()
    serializer_class = DrinksSerializer

class FoodsViewSet(viewsets.ModelViewSet):
    queryset = Foods.objects.all()
    serializer_class = FoodsSerializer

class OrdersViewSet(viewsets.ModelViewSet):
    queryset = Orders.objects.all()
    serializer_class = OrdersSerializer

class MemberViewSet(viewsets.ModelViewSet):
    queryset = Member.objects.all()
    serializer_class = MemberSerializer

def index(request):
    orders = list(Orders.objects.filter(user_name=str(request.COOKIES['name'])).order_by('-datetime').values())
    
    
    return render(request, 'products/index.html', locals())
def products(request):
    foods = Foods.objects.all()
    drinks = Drinks.objects.all()
    print(foods,drinks)
    return render(request, 'products/products.html', locals())

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>首頁內容</h1>
    <br>
    <h2>現在時間{{now}}</h2>
{% endblock %}

member/templates/member/create.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
        {% csrf_token %} 
        
        <div class="form-grouprow" style="position: relative;left: 40%;">
            <label for="username">姓名</label>
            <input style="width: 30%" type="text" class="form-control" name="username" id="username" placeholder="User Name">
        </div>
        <div class="form-grouprow" style="position: relative;left: 40%;">
            <label for="password">密碼</label>
            <input style="width: 30%" type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
        <div class="form-grouprow" style="position: relative;left: 40%;">
            <label for="useremail">電子郵件</label>
            <input style="width: 30%" type="email" class="form-control" name="useremail" id="useremail" placeholder="User Email">
        </div>
        <div class="form-grouprow" style="position: relative;left: 40%;">
            <label for="userbirth">生日</label>
            <input style="width: 30%" type="date" class="form-control" name="userbirth" id="userbirth" placeholder="Birthday">
        </div>
        <div class="form-grouprow" style="position: relative;left: 54%;margin-top: 10px">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-bath" aria-hidden="true"></i>註冊</button>
            </div>
        </div>
    
    </form>
{% endblock %}

member/templates/member/forget.html
{% extends 'base.html' %}
{%load static %}
{% block content %}
<script type="text/javascript" src="{% static 'scripts/selectivizr.js' %}"></script>
<link rel="stylesheet" href="{% static 'styles/style.css' %}" type="text/css" />
<noscript><link rel="stylesheet" href="{% static 'styles/fallback.css' %}" /></noscript>
      <form method="POST" >
            {%csrf_token%}
                <div class="login">忘記密碼?</div>
                <div class="username-text">電子郵件</div>             
                <div class="password-field">
                    <input type="password" class="form-control" name="useremail" id="useremail" placeholder="Email" />
                </div>
            
        
                <input type="submit" name="submit" value="GO"  />
            </form>
{% endblock %}

member/templates/member/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script type="text/javascript" src="{% static 'scripts/selectivizr.js' %}"></script>
<link rel="stylesheet" href="{% static 'styles/style.css' %}" type="text/css" />
<noscript><link rel="stylesheet" href="{% static 'styles/fallback.css' %}" /></noscript>
<form method="POST" >
    {%csrf_token%}
        <div class="login">登入</div>
        <div class="username-text">使用者名稱:</div>
        <div class="password-text">密碼:</div>
        <div class="username-field">
            <input type="text" name="username" id="username" aria-describedby="emailHelp" placeholder="username" style="margin: 7.5px"/>
        </div>
        <div class="password-field">
            <input type="password" class="form-control" name="userpassword" id="userpassword" placeholder="Password" />
        </div>
        
        <input type="checkbox" name="rememberme" id="exampleCheck1"><label for="rememberme">記住我</label>

        <div class="forgot-usr-pwd"><a href="{% url 'member:forget' %}">忘記密碼?</a></div>
        <input type="submit" name="submit" value="GO"  />
    </form>
    
{% endblock %}

member/templates/member/memberarea.html
{% extends 'base.html' %}
{%block content %}

{%endblock%}

products/templates/products/index.html
{% extends 'base.html'%}
{% block content %}
<h2>{{request.COOKIES.name}}您好</h2>
<table style="border:2px solid black;width: 100%;text-align: center;font-size: 24px">
    <thead style="border:1px solid black">
        <tr >
            <th style="border:3px solid black">購物編號</th>
            <th style="border:3px solid black">購物品名</th>
            <th style="border:3px solid black">購物價格</th>
            <th style="border:3px solid black">購物數量</th>
            <th style="border:3px solid black">購物總價格</th>
            <th style="border:3px solid black">購物時間</th>
            
        </tr>
    </thead>
<tbody>
{% for order in orders %}
{% with id=order.order_number price=order.price qt=order.qt %}
<tr>
    <td style="border:1px solid rgb(169, 135, 207)">{{order.order_number}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{order.product_name}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{order.price}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{order.qt}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{% widthratio price 1 qt %}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{order.datetime}}</td>
</tr>



{% endwith %}
{% endfor %}
</tbody>
</table>

{% endblock %}

products/templates/products/products.html
{% extends 'base.html'%}
{% block content %}
<h2>{{request.COOKIES.name}}您好</h2>
<table style="border:2px solid black;width: 100%;text-align: center;font-size: 24px">
    <thead style="border:1px solid black">
        <tr >
            <th style="border:3px solid black">商品名稱</th>
            <th style="border:3px solid black">商品價格</th>
            <th style="border:3px solid black">商品數量</th>
        </tr>
    </thead>
<tbody>
{% for food in foods %}
<tr>
    <td style="border:1px solid rgb(169, 135, 207)"><img src="{{food.image}}" width='150px' height="150px">{{food.name}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{food.price}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{food.qt}}</td>

</tr>
{% endfor %}
{% for drink in drinks %}
<tr>
    <td style="border:1px solid rgb(169, 135, 207)"><img src="{{drink.image}}" width='150px' height="150px">{{drink.name}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{drink.price}}</td>
    <td style="border:1px solid rgb(169, 135, 207)">{{drink.qt}}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock %}

products/templates/products/test.html
<!DOCTYPE html>
<html>
<body>
  <iframe id="chat" style="width: 400px; height: 400px;" src='https://webchat.botframework.com/embed/FirstBot0621?s=2sQFBD8C_3g.cwA.a6w.zJDtqjwpLJpJ4VxrYHGkMv5wJnvqVFAEMhxx9otRK4I'></iframe>
</body>
<script>

    var xhr = new XMLHttpRequest();
    xhr.open('GET', "https://webchat.botframework.com/api/tokens", true);
    xhr.setRequestHeader('Authorization', 'BotConnector ' + 'YOUR SECRET HERE');
    xhr.send();
    xhr.onreadystatechange = processRequest;

    function processRequest(e) {
      if (xhr.readyState == 4  && xhr.status == 200) {
        var response = JSON.parse(xhr.responseText);
        document.getElementById("chat").src="https://webchat.botframework.com/embed/lucas-direct-line?t="+response
      }
    }

  </script>
</html>